services:
    clm_roles_helper:
           class: ArgoMCMBuilder\UserBundle\Services\RolesHelper
           arguments: ['%security.role_hierarchy.roles%']
    clm.user.form.registration:
        class: ArgoMCMBuilder\UserBundle\Form\Type\RegistrationType
        arguments: ['%fos_user.model.user.class%', '@clm_roles_helper', '@service_container']
        tags:
            - { name: form.type, alias: clm_user_registration }
    clm.user.form.profile:
            class: ArgoMCMBuilder\UserBundle\Form\Type\ProfileType
            arguments: ['%fos_user.model.user.class%', '@clm_roles_helper', '@security.context']
            tags:
                - { name: form.type, alias: clm_user_profile }
    clm.user.form.group:
            class: ArgoMCMBuilder\UserBundle\Form\Type\GroupType
            arguments: ['%fos_user.model.group.class%', '@clm_roles_helper']
            tags:
                - { name: form.type, alias: clm_user_group }
 #   clm.file.twig.extension:
 #           class: %clm.file.twig.extension.class%
 #           tags:
 #               - { name: twig.extension }
    app.user_checker:
        class: ArgoMCMBuilder\UserBundle\Handler\UserChecker
        arguments: ['@service_container']
    app.guest_connect:
        class: ArgoMCMBuilder\UserBundle\Handler\GuestConnect
        arguments: ['@service_container', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }