'use strict';

const defaultFontList = {
    "fonts":[
        {"name":"Merck", "url":"/fonts/merck-webfont/merck-webfont.ttf"},
        {"name":"FuturaStd-CondensedLight", "url":"/fonts/FuturaStd-CondensedLight/FuturaStd-CondensedLight.otf"},
        {"name":"ProximaNova", "url":"/fonts/proximanova-regular-webfont/proximanova-regular-webfont.otf"},
        {"name":"ProximaNovaBold", "url":"/fonts/proximanova-bold-webfont/proximanova-bold-webfont.ttf"},
        {"name":"ProximaNovaSemibold", "url":"/fonts/proximanova-semibold-webfont/proximanova-semibold-webfont.otf"},
        {"name":"MerckPro", "url":"/fonts/MerckSansSerifPro/MerckSansSerifPro.ttf"},
        {"name":"MerckBold", "url":"/fonts/MerckSansSerifPro-Bold/MerckSansSerifPro-Bold.ttf"},
        {"name":"Montserrat", "url":"/fonts/Montserrat-Regular/Montserrat-Regular.otf"},
        {"name":"OpenSans", "url":"/fonts/opensans-regular-webfont/opensans-regular-webfont.ttf"},
        {"name":"Asul", "url":"/fonts/asul-regular/asul-regular.eot"},
        {"name":"JosefinSans", "url":"/fonts/JosefinSans-Regular/JosefinSans-Regular.ttf"},
        {"name":"LeagueGothic", "url":"/fonts/LeagueGothic-Regular/LeagueGothic-Regular.otf"},
        {"name":"MerriweatherSans", "url":"/fonts/MerriweatherSans-Regular/MerriweatherSans-Regular.otf"},
        {"name":"Overpass", "url":"/fonts/overpass-regular/overpass-regular.otf"},
        {"name":"CabinSketch", "url":"/fonts/cabinsketch-regular/cabinsketch-regular.eot"},
        {"name":"NewsCycle", "url":"/fonts/NewsCycle-Regular/NewsCycle-Regular.ttf"},
        {"name":"RajdhaniBold", "url": "/fonts/Rajdhani-Bold/Rajdhani-Bold.ttf"},
        {"name":"RajdhaniLight", "url": "/fonts/rajdhani-light-webfont/rajdhani-light-webfont.ttf"},
        {"name":"RajdhaniMedium", "url": "/fonts/rajdhani-medium-webfont/rajdhani-medium-webfont.ttf"},
        {"name":"RajdhaniRegular", "url": "/fonts/Rajdhani-Regular/Rajdhani-Regular.ttf"},
        {"name":"RajdhaniSemiBold", "url": "/fonts/Rajdhani-Semibold/Rajdhani-Semibold.ttf"},
        {"name":"futuraBdCn", "url": "/fonts/futurabdcn/futurabdcn.ttf"},
        {"name":"futuraBlackBold", "url": "/fonts/futurablackbold/futurablackbold.ttf"},
        {"name":"futuraBold", "url": "/fonts/futurabold/futurabold.ttf"},
        {"name":"futuraBoldItalic", "url": "/fonts/futuraBoldItalic/futurabolditalic.ttf"},
        {"name":"futuraBook", "url": "/fonts/futuraBook/futurabook.ttf"},
        {"name":"futuraBookItalic", "url": "/fonts/futuraBookItalic/futurabookitalic.ttf"},
        {"name":"futuraExtraBlack", "url": "/fonts/futuraExtraBlack/futuraextrablack.ttf"},
        {"name":"futuraExtrablackItalic", "url": "/fonts/futuraExtrablackItalic/futuraextrablackitalic.ttf"},
        {"name":"futuraHeavy", "url": "/fonts/futuraHeavy/futuraheavy.ttf"},
        {"name":"futuraHeavyItalic", "url": "/fonts/futuraHeavyItalic/futuraheavyitalic.ttf"},
        {"name":"futuraLightBt", "url": "/fonts/futuraLightBt/futuralightbt.ttf"},
        {"name":"futuraLightItalic", "url": "/fonts/futuraLightItalic/futuralightitalic.ttf"},
        {"name":"futuraLtCnLight", "url": "/fonts/futuraLtCnLight/futuraltcnlight.ttf"},
        {"name":"futuramediumBt", "url": "/fonts/futuramediumBt/futuramediumbt.ttf"},
        {"name":"futuraMediumItalic", "url": "/fonts/futuraMediumItalic/futuramediumitalic.ttf"},
        {"name":"futuraMediumMdCn", "url": "/fonts/futuraMediumMdCn/futuramediummdcn.ttf"},
        {"name":"GilroyBold", "url": "/fonts/GilroyBold/GilroyBold.ttf"},
        {"name":"GilroyBoldItalic", "url": "/fonts/GilroyBoldItalic/GilroyBoldItalic.ttf"},
        {"name":"GilroyLight", "url": "/fonts/GilroyLight/GilroyLight.ttf"},
        {"name":"GilroyLightItalic", "url": "/fonts/GilroyLightItalic/GilroyLightItalic.ttf"},
        {"name":"GilroyMedium", "url": "/fonts/GilroyMedium/GilroyMedium.ttf"},
        {"name":"GilroyMediumItalic", "url": "/fonts/GilroyMediumItalic/GilroyMediumItalic.ttf"},
        {"name":"GilroyRegular", "url": "/fonts/GilroyRegular/GilroyRegular.ttf"},
        {"name":"GilroyRegularItalic", "url": "/fonts/GilroyRegularItalic/GilroyRegularItalic.ttf"},
        {"name":"GilroySemiBold", "url": "/fonts/GilroySemiBold/GilroySemiBold.ttf"},
        {"name":"GilroySemiBoldItalic", "url": "/fonts/GilroySemiBoldItalic/GilroySemiBoldItalic.ttf"},
        {"name":"FuturaBTMediumItalic", "url": "/fonts/FuturaBTMediumItalic/FuturaBTMediumItalic.ttf"},
        {"name":"FuturaBTMedium", "url": "/fonts/FuturaBTMedium/FuturaBTMedium.ttf"},
        {"name":"FuturaBTCondMedium", "url": "/fonts/FuturaBTCondMedium/FuturaBTCondMedium.ttf"},
        {"name":"SignPainterHouse", "url": "/fonts/signPainter/signPainter.ttf"},
        {"name":"EagleBook", "url": "/fonts/EagleBook/EagleBook.ttf"},
        {"name":"UniversLTStdBoldCn", "url": "/fonts/UniversLTStdBoldCn/UniversLTStdBoldCn.ttf"},
        {"name":"WhitneyBold", "url": "/fonts/WhitneyBold/WhitneyBold.ttf"},
        {"name":"WhitneyBoldItalic", "url": "/fonts/WhitneyBoldItalic/WhitneyBoldItalic.ttf"},
        {"name":"WhitneyBook", "url": "/fonts/WhitneyBook/WhitneyBook.ttf"},
        {"name":"WhitneyBookItalic", "url": "/fonts/WhitneyBookItalic/WhitneyBookItalic.ttf"},
        {"name":"WhitneyMedium", "url": "/fonts/WhitneyMedium/WhitneyMedium.ttf"},
        {"name":"WhitneyMediumItalic", "url": "/fonts/WhitneyMediumItalic/WhitneyMediumItalic.ttf"},
        {"name":"WhitneySemiblod", "url": "/fonts/WhitneySemiblod/WhitneySemiblod.ttf"},
        {"name":"WhitneySemiboldItalic", "url": "/fonts/WhitneySemiboldItalic/WhitneySemiboldItalic.ttf"},
        {"name":"AvenirMedium", "url": "/fonts/AvenirLTStdMedium/AvenirLTStdMedium.ttf"},
        {"name":"AvenirLightOblique", "url": "/fonts/AvenirLTStdLightOblique/AvenirLTStdLightOblique.ttf"},
        {"name":"AvenirLight", "url": "/fonts/AvenirLTStdLight/AvenirLTStdLight.ttf"},
        {"name":"AvenirBlack", "url": "/fonts/AvenirLTStdBlack/AvenirLTStdBlack.ttf"},
        {"name":"RotisSansSerifStdBold", "url": "/fonts/RotisSansSerifStd-Bold/RotisSansSerifStd-Bold.ttf"},
        {"name":"RotisSansSerifStdExtraBold", "url": "/fonts/RotisSansSerifStd-ExtraBold/RotisSansSerifStd-ExtraBold.ttf"},
        {"name":"RotisSansSerifStdItalic", "url": "/fonts/RotisSansSerifStd-Italic/RotisSansSerifStd-Italic.ttf"},
        {"name":"RotisSansSerifStdLight", "url": "/fonts/RotisSansSerifStd-Light/RotisSansSerifStd-Light.ttf"},
        {"name":"RotisSansSerifStdLightItalic", "url": "/fonts/RotisSansSerifStd-LightItalic/RotisSansSerifStd-LightItalic.ttf"},
        {"name":"RotisSansSerifStdRegular", "url": "/fonts/RotisSansSerifStd-Regular/RotisSansSerifStd-Regular.ttf"},
        {"name": "avenirHeavy", "url": "/fonts/avenirHeavy/avenirHeavy.woff"},
        {"name": "arialBold", "url": "/fonts/arialBold/arialBold.woff"},
        {"name": "arialItalic", "url": "/fonts/arialItalic/arialItalic.woff"},
        {"name": "arialBoldItalic", "url": "/fonts/arialBoldItalic/arialBoldItalic.woff"},
        {"name": "RobotoBlack", "url": "/fonts/Roboto-Black/Roboto-Black.woff"},
        {"name": "RobotoBlackItalic", "url": "/fonts/Roboto-BlackItalic/Roboto-BlackItalic.woff"},
        {"name": "RobotoBold", "url": "/fonts/Roboto-Bold/Roboto-Bold.woff"},
        {"name": "RobotoBoldCondensed", "url": "/fonts/Roboto-BoldCondensed/Roboto-BoldCondensed.woff"},
        {"name": "RobotoBoldCondensedItalic", "url": "/fonts/Roboto-BoldCondensedItalic/Roboto-BoldCondensedItalic.woff"},
        {"name": "RobotoBoldItalic", "url": "/fonts/Roboto-BoldItalic/Roboto-BoldItalic.woff"},
        {"name": "RobotoCondensed", "url": "/fonts/Roboto-Condensed/Roboto-Condensed.woff"},
        {"name": "RobotoCondensedItalic", "url": "/fonts/Roboto-CondensedItalic/Roboto-CondensedItalic.woff"},
        {"name": "RobotoItalic", "url": "/fonts/Roboto-Italic/Roboto-Italic.woff"},
        {"name": "RobotoLight", "url": "/fonts/Roboto-Light/Roboto-Light.woff"},
        {"name": "RobotoLightItalic", "url": "/fonts/Roboto-LightItalic/Roboto-LightItalic.woff"},
        {"name": "RobotoMedium", "url": "/fonts/Roboto-Medium/Roboto-Medium.woff"},
        {"name": "RobotoMediumItalic", "url": "/fonts/Roboto-MediumItalic/Roboto-MediumItalic.woff"},
        {"name": "RobotoRegular", "url": "/fonts/Roboto-Regular/Roboto-Regular.woff"},
        {"name": "RobotoThin", "url": "/fonts/Roboto-Thin/Roboto-Thin.woff"},
        {"name": "RobotoThinItalic", "url": "/fonts/Roboto-ThinItalic/Roboto-ThinItalic.woff"}
    ]
};

module.exports = defaultFontList;