
var SLConfig = {
    "current_user": {
        "id": 583976,
        "username": "houssemzitoun",
        "name": "Houssem ZITOUN",
        "description": null,
        "thumbnail_url": "",
        "pro": false,
        "team_id": null,
        "settings": {
            "id": 429271,
            "present_controls": true,
            "present_upsizing": true,
            "present_notes": true,
            "editor_grid": true,
            "editor_snap": true,
            "developer_mode": false,
            "speaker_layout": null
        },
        "email": "h.z@mail.fr",
        "notify_on_receipt": true,
        "billing_address": null,
        "editor_tutorial_completed": true,
        "manually_upgraded": false,
        "deck_user_editor_limit": 1
    },
    "deck": {
        "id": 814055,
        "slug": "rikimi",
        "title": "Rikimi",
        "description": "",
        "visibility": "all",
        "published_at": "2016-09-30T10:35:10.355Z",
        "sanitize_messages": null,
        "thumbnail_url": "",
        "view_count": 0,
        "user": {
            "id": 583976,
            "username": "houssemzitoun",
            "name": "Houssem ZITOUN",
            "description": null,
            "thumbnail_url": "",
            "pro": false,
            "team_id": null,
            "settings": {"id": 429271, "present_controls": true, "present_upsizing": true, "present_notes": true}
        },
        "background_transition": null,
        "transition": null,
        "theme_id": null,
        "theme_font": "montserrat",
        "theme_color": "white-blue",
        "auto_slide_interval": 0,
        "comments_enabled": false,
        "forking_enabled": false,
        "rolling_links": false,
        "center": false,
        "should_loop": false,
        "share_notes": null,
        "slide_number": null,
        "rtl": false,
        "version": 2,
        "collaborative": null,
        "deck_user_editor_limit": 1,
        "data_updated_at": 1475233222766,
        "font_typekit": null,
        "font_google": null,
        "access_token": "svsuxwQHhJRqsxr3WmPoxCPFrnsr",
        "notes": {}
    }
};
