imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@DashboardBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    trans: "%translation%"
    clm.file.twig.extension.class: ArgoMCMBuilder\UserBundle\Twig\Extension\FileExtension
    knp_menu.renderer.twig.options:
          currentClass: active
    media_directory: '%kernel.root_dir%/../web/uploads/'
    pdf_directory_print: '%kernel.root_dir%/../web/slides-pdf/'
    main_directory: '%kernel.root_dir%/../'
    pdf_directory: '.eu-west-1.argolife.internal/'
    s3_directory: '/argolife-mcm-export/pdf/'
    pdf_thumbs: '_Tmp_Pdf'
    media_directory_pdf: '%kernel.root_dir%/../web/uploads/pdf/'
    media_directory_image: '%kernel.root_dir%/../web/uploads/images/'
    zip_deep_directory: '%kernel.root_dir%/../web/zip_output/mi_deep' # le rendering
    zip_wide_directory: '%kernel.root_dir%/../web/zip_output/veeva_wide' # le rendering
    veeva_deep_framework: '%kernel.root_dir%/../web/zip_input/frameworkVeevaDeep' # source
    mi_deep_framework: '%kernel.root_dir%/../web/zip_input/frameworkMiDeep' # source
    mi_wide_framework: '%kernel.root_dir%/../web/zip_input/frameworkMiWide' # source
    veeva_wide_framework: '%kernel.root_dir%/../web/zip_input/frameworkVeevaWide' # source
    veeva_wide_framework_thumbs: '/zip_input/frameworkVeevaWide/shared/dev_framework_shared/shared_thumb.jpg' # source
    css_merck: '%kernel.root_dir%/../web/zip_input/Merck' # source
    mcm_survey: '%kernel.root_dir%/../web/zip_input/Mcm_survey' # source
    web_directory: '%kernel.root_dir%/../web'
    thumbnails: '%kernel.root_dir%/../web/%presentations_thumbnails%'
    thumbs: '/../%presentations_thumbnails%'
    phantomjsmodels: '%kernel.root_dir%/../web/js/phantom_models/'
    decktape_path: '%kernel.root_dir%/../decktape'
    session_max_idle_time: 1800
    tag_version: 0.70.337.137-RC #0.70.337.95-RC #V0.31.239.47-a16 #V0.30.235.Bennani #V0.23.198.40.a64
    dropzone_file_extensions: 'image/*,application/pdf,video/mp4'
    dropzone_pdf_size: '50' #la taille doit être en mo
    dropzone_image_size: '2.5' #la taille doit être en mo
    dropzone_video_size: '80' #la taille doit être en mo
    max_size_zip: '225' #la taille doit être en mo
#Piwik Config same for all
    piwik_domain: mcm-builder.com
    piwik_url: piwik.argolife.fr/
    piwik_idSite: 1
    piwik_token_auth: c14adbb50ae1be2f0d63f8da58171871
    aws:
        region                  : 'eu-west-1'
        env_bucket              : 'veeva-summit'
        aws_access_key_id       : 'AKIAIBJ5TEFCI26MLU2A'
        aws_secret_access_key   : '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'
        aws_admin_secret_key    : 'pH+Ppc9SbixckiH5D0LGmTLx2f4ktow44tN0tPbm'
        upload_bucket           : 'mcm-media-librairie-dev'
        resize_bucket           : 'mcm-media-resize'
        apiVersion              : '2006-03-01'
        acl                     : "public-read"
        sizeLimit               : "5120000"
        widthCompare            : "1024"
        expectedHostName        : "http://s3.amazonaws.com"


framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        #handler_id:  session.handler.pdo
        handler_id:  snc_redis.session.handler
    fragments:       ~
    http_method_override: true
    test: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        clm_logo_path: 'logo.png'
        tag_version:    "%tag_version%"
        piwik_domain:   "%piwik_domain%"
        pdf_size: "%dropzone_pdf_size%"
        image_size: "%dropzone_image_size%"
        video_size: "%dropzone_video_size%"
        file_extension: "%dropzone_file_extensions%"
        thumb_url: "%presentations_thumbnails%"
        phantomjs_models: "%phantomjsmodels%"
        phantom_preview: "%phantom_preview%"
        s3_domain: "%s3_domain%"
        s3_directory: "%s3_directory%"
        web_directory: "%web_directory%"
        trans: "%trans%"
    form:
        resources:
            - SimpleThingsFormExtraBundle:Form:field_type_help.html.twig
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                Json_Append: Syslogic\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonAppend
                Json_Array: Syslogic\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonArray
                Json_ArrayAppend: Syslogic\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonArrayAppend
                JSON_CONTAINS: Syslogic\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains
                JSON_CONTAINS_PATH: Syslogic\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContainsPath
                Json_Insert: Syslogic\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonInsert

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: "%mailer_encryption%"
    port:       "%mailer_port%"
    #spool:     { type: memory }
    logging:   "%kernel.debug%"

# FOSUser Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: ArgoMCMBuilder\UserBundle\Entity\User
    service:
            mailer: fos_user.mailer.twig_swift
    from_email:
                address:        mcmadmin@argolife.fr
                sender_name:    Argolife
    group:
        group_class: ArgoMCMBuilder\UserBundle\Entity\Group
        form:
            type: clm_user_group
            validation_groups: [ClmRegistration]
    registration:
            form:
                type: clm_user_registration
                validation_groups: [ClmRegistration]
    profile:
            form:
                 type: clm_user_profile
    resetting:
                email:
                    from_email:
                        address:        mcmadmin@argolife.fr
                        sender_name:    Argolife

# Knp menu
knp_menu:
    twig:
        template: ArgoMCMBuilder:BackOfficefficeBundle:Menu:knp_menu.html.twig

# Intl Extension
services:

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    session.handler.pdo:
            class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
            public:    false
            arguments:
                - 'mysql:host=%database_host%;port=null;dbname=%database_name%'
                - { db_username: '%database_user%', db_password: '%database_password%' }
            services:
                a_service:
                    class: Aws\Credentials\Credentials
                    arguments:
                        - a-different-fake-key
                        - a-different-fake-secret
fm_elfinder:
    instances:
        ckeditor:
            editor:           ckeditor
            fullscreen:       false
            include_assets:   true
            connector:
                debug:        true
                roots:
                    uploads:
                        driver:           LocalFileSystem
                        path:             your_path_in_public_directory
                        upload_allow:     ['image/png', 'image/jpg', 'image/jpeg', 'image/gif', 'application/zip', 'audio/mpeg', 'text/csv', 'video/mp4', 'video/webm', 'application/pdf']
                        upload_deny:      ['all']
                        upload_max_size:  8M
ivory_ck_editor:
    default_config:    my_custom_config
    configs:
        my_custom_config:
            toolbar:                    basic
            filebrowserBrowseRoute:     elfinder
            filebrowserBrowseRouteParameters:
                instance: ckeditor
                homeFolder: uploads
    plugins:
        pbckcode:
            path:                       '/bundles/unixeliaapp/ckeditor/pbckcode/'
            filename:                   'plugin.js'
    default_config:    my_custom_config
    configs:
        my_custom_config:
            toolbar:                    ['pbckcode']
            extraPlugins:               'pbckcode'
            pbckcode:                   { highlighter : 'HIGHLIGHT', tab_size : '4', theme : 'github',  modes :  [['Text', 'text'],['HTML', 'html'], ['CSS', 'css'], ['PHP', 'php'], ['JS', 'javascript'], ['YAML', 'yaml'], ['JSON', 'json'], ['SQL', 'sql'], ['Bash', 'bash']], js : "https://cdn.jsdelivr.net//ace/1.1.4/noconflict/" }
fos_rest:
    format_listener:
          rules:
              - { path: ^/api/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
              - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
    routing_loader:
        default_format: json
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json: true
        templating_formats:
            html: true

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: '%session_handler_redis_save_path%'
        session:
            type: predis
            alias: session
            dsn: '%session_handler_redis_save_path%'
    session:
        client: session
        prefix: SESSION:
        ttl: 1800 # 30 minute

webfactory_piwik:
    # Required, no default. Must be set to the site id found in the Piwik control panel
    site_id: "%piwik_idSite%"
    # Required, has default. Usually, you only want to include the tracking code in a production environment
    #disabled: "%kernel.debug%"
    disabled : "%piwik_disabled%"
    # Required. no default. Hostname and path to the piwik host.
    piwik_host: "%piwik_url%"
    # Required, has default. Path to the tracking script on the host.
    tracker_path: "/js/"
#config guzzle
guzzle:
    # (de)activate logging/profiler; default: %kernel.debug%
    logging: true

    clients:
        auth_crm:
            base_url: "https://vv-agency-argonautes.veevavault.com"
            headers:
                Accept: "application/json"
        tools_binder:
            base_url: "https://vv-agency-argonautes.veevavault.com"
            headers:
                Accept: "application/json"

simple_things_form_extra:
    help_extension: true

aws:
    version: 2006-03-01
    region: eu-west-1
    credentials:
        key: "AKIAIQD2ECGCACM6ETUA"
        secret: "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" # this will be escaped as '@not-a-real-secret'
    DynamoDb:
        region: us-west-2
    S3:
        version: '2006-03-01'
    CloudSearchDomain:
        endpoint: https://search-with-some-subdomain.us-east-1.cloudsearch.amazonaws.com