imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
parameters:
    locksession: true


back_office:
  decktapes_connection:
        host: 'ec2-52-205-143-109.compute-1.amazonaws.com'
        user: 'ubuntu'
        key_path: '/home/argo/illiads/merck/projects/mclmbuilder/SH/Devspace.pem'

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  rotating_file
            max_files: 10
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
