<?php

namespace ArgoMCMBuilder\PresentationBundle;
use Doctrine\DBAL\Types\Type;
use ArgoMCMBuilder\PresentationBundle\Type\JsonDocType;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class PresentationBundle extends Bundle
{
    public function __construct()
    {
    }
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        $em = $this->container->get('doctrine.orm.entity_manager');
        Type::addType('json_doc', JsonDocType::class);
        $em->getConnection()->getDatabasePlatform()->registerDoctrineTypeMapping('JSON', 'json_doc');
    }

}
